# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    environment:
      - OPEN_WEATHER_APP_ID=0db462d7cd3cd90563fd7059cbe2a4f5
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY="django-insecure-8jc=7--=+!ak=d*v!n)qt__zurp1t3k#4p4op)s&w3p=^ba0"
      - ENVIRONMENT=development
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  flower:
    build: .
    command: celery -A config --broker="redis://redis:6379/0" flower
    volumes:
      - .:/code
    ports:
      - 5557:5555
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
