# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECRET_KEY=django-insecure-8jc=7--=+!ak=d*v!n)qt__zurp1t3k#4p4op)s&w3p=^ba0"
      #- "REDIS_HOST=redis"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine


  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis


  celery-beat:
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  flower:
    build: .
    command: celery -A config --broker="redis://redis:6379/0" flower
    volumes:
      - .:/code
    ports:
      - 5557:5555
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
