# Generated by Django 4.0.4 on 2022-04-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0002_alter_entry_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="title",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
