# Generated by Django 4.0.5 on 2022-06-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('voivodeship', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='WeatherInCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.SmallIntegerField()),
                ('pressure', models.PositiveSmallIntegerField()),
                ('humidity', models.PositiveSmallIntegerField()),
                ('measurement_time', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=50)),
                ('weather_type', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Weather in the City',
            },
        ),
    ]
