# Generated by Django 4.0.5 on 2022-06-14 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_remove_city_voivodeship'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='voivodeship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weather.voivodeship'),
            preserve_default=False,
        ),
    ]
