# Generated by Django 4.0.5 on 2022-06-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_city_unique city in voivodeship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherincity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='weather.city'),
        ),
    ]
