# Generated by Django 4.0.5 on 2022-06-22 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_alter_weatherincity_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherInVoivodeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.SmallIntegerField()),
                ('pressure', models.PositiveSmallIntegerField()),
                ('humidity', models.PositiveSmallIntegerField()),
                ('measurement_time', models.DateTimeField(auto_now_add=True)),
                ('voivodeship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='weather.voivodeship')),
            ],
            options={
                'verbose_name_plural': 'Weather in the Voivodeship',
            },
        ),
    ]
