# Generated by Django 4.0.5 on 2022-06-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_weatherinvoivodeship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherinvoivodeship',
            options={'verbose_name_plural': 'Weather in the Voivodeships'},
        ),
    ]
